### ISSUE TITLE
Comes up as a 'lab' in learn

### ISSUE THREAD

**Issue by jjseymour** [learn-co-curriculum/introduction-to-es6#3]
Unless I am missing something - I believe this should only be a ReadMe. In learn there is a prompt to 'Fork this lab', 'Run Local Tests', 'Submit Pull Request'

**Comment by AnnJohn** [comment]
hey @jjseymour it should be deployed as a Readme. I toggled it a couple of times in Learn between lab and readme (since that sometimes does the trick). Could you check and see if it's a Readme now? thanks

**Comment by jjseymour** [comment]
Hey @AnnJohn - that fixed it! I am going to close this issue.
